#!/bin/bash

#**
#*Signature
# Ubuntu 22.04 LTS, Apache2, Wordpress, SSL, PHP-FPM - 8.1, Mysql - 8, Phpmyadmin, Zabbix - 6 LTS, Vsftpd, Backuc custom script
#*Installing set Linux, Apache, MySQL, PHP (LAMP) in Ubuntu 20.04. PHP will work as Apache module. 
#*https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-20-04-ru
#*Progress-bar http://linuxoid.in/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81-%D0%B1%D0%B0%D1%80_%D0%B4%D0%BB%D1%8F_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B2
#*Progress-bar v2
#*phpmyadmin https://losst.pro/ustanovka-phpmyadmin-ubuntu-18-04
#*https://tproger.ru/articles/set-up-and-configure-an-apache-server/ 
#bash and mysql https://stackoverflow.com/questions/20033648/how-to-run-mysql-command-on-bash
#**

#Сжатие mod deflate \ nginx gzip
#HTTP2.0

#**
#*Global variable
#**
#**
#*Global variable
#**
#system user
SYSTEM_USER_NAME="adminer";
SYSTEM_USER_PASSWORD="rokit555";

#server
MAIN_DOMAIN="scriptcraft.site";
SUBDOMAINS=(
    "dev.scriptcraft.site" 
    "stg.scriptcraft.site"
    );

#mysql    
MYSQL_ROOT_PASSWORD="root555";
MYSQL_ADMIN_USER="adminer";
MYSQL_ADMIN_PASSWORD="rokit555";

#phpmyadmin
PMA_ADMIN_USER="adminer";
PMA_AUTH_PASS="rokit555";
PMA_HIDDEN_URI=$(head -c 100 /dev/urandom | base64 | sed 's/[+=/A-Z]//g' | tail -c 9);

#wordpress
WP_SITE_TITLE="TEST";
WP_ADMIN_USER="adminer";
WP_ADMIN_PASSWORD="rokit555";
WP_ADMIN_EMAIL="scriptcraft.site@gmail.com";
WP_DB_PREFIX="wp_";
WP_SITE_DESCRIPTION="My tets site";
WP_PERMALINK_STRUCTURE="/%postname%/";
WP_THEME_NAME="twentytwentyone";

#zabbix
ZABBIX_PASSWORD="rokit555";


#other
SWD=${0%/*};
INSTALL_SSL="NO";
IP=$(wget -qO- ifconfig.me);
ADMIN_EMAIL="scriptcraft.site@gmail.com";
PORT=":9999/";

#**
#*Start check
#**
if [[ $(id -u) -ne 0 ]]; then
    echo $(id -u);
    echo -e "\n You are not root. \n Run the command sudo -i. \n Enter you password for current user. \n And start this script again.\n $0\n";
    exit 1;
fi

declare -A check_release;
check_release["dist_name"]="false";
check_release["version"]="false";

while read string; do
    IFS="=" read name value <<< "$string";
    value=${value//\"/};

    if [[ $name == "NAME" && $value == "Ubuntu" ]]; then
        check_release["dist_name"]="true";
    fi

    if [[ $name == "VERSION_ID" && $value == "22.04" ]]; then
        check_release["version"]="true";
    fi
done < /etc/os-release

if [[ "false" == ${check_release["dist_name"]} || "false" == ${check_release["version"]} ]]; then
    echo -e "The script has not been tested for your distribution and/or its version.\nThe script is designed for Ubuntu 22.04.";
    exit 1;
fi

#**
#*Functions helpers
#**
good_print(){
    if [[ "" == $1 ]]; then
        echo -e "The function expects a string in the first parameter \n";
        return 1;
    fi
    GREEN="\e[32m"; 
    ENDCOLOR="\e[0m";
    echo -e "${GREEN}$1${ENDCOLOR}";
    return 0;
}

bad_print(){
    if [[ "" == $1 ]]; then
        echo -e "The function expects a string in the first parameter \n";
        return 1;
    fi
    RED="\e[31m";
    ENDCOLOR="\e[0m";
    echo -e "${RED}$1${ENDCOLOR}";
    return 0;
}

get_approval(){
    good_print "Are you ready to continue? yes: Y or y,  no: N or n";
    read response;
    if [[ $response == "N" || $response == "n"  ]]; then
        message="Do you want to interrupt the installation? yes: Y or y,  no: N or n";
        bad_print "$message";
        read response;
        if [[ $response == "Y" || $response == "y"  ]]; then
            exit 1;
        fi
    fi
    return 0;
}

#**
#*Functions actions
#**
preparatory_step(){
    good_print "***PREPARATORY STEP***";
    sleep 1;
    sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf;
    apt-get -y update;
    apt-get -y upgrade; 
    apt-get -y install -y vim tmux htop git curl wget unzip zip gcc build-essential make;
    good_print "Step 0 [Preparatory step].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

create_user(){
    good_print "***CREATE USER***";
    sleep 1;
    useradd -s /bin/bash -d /home/$SYSTEM_USER_NAME -m $SYSTEM_USER_NAME;
    echo -e "${SYSTEM_USER_PASSWORD}\n${SYSTEM_USER_PASSWORD}\n" | passwd $SYSTEM_USER_NAME;
    good_print "Step 1 [Create user].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_apache(){
    good_print "***INSTALL APACHE2***";
    sleep 1;
    apt-get -y install apache2;
    if [[ 0 != $? ]]; then
        bad_print "install apach2 failed";
        return 1;
    fi
    
    good_print "Step 2 [Install apache2].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

configuration_ufw(){
    good_print "***CONFIGURATION UFW***";
    sleep 1;
    ufw allow in "Apache";
    ufw allow in "OpenSSH";
    ufw allow 20,21,990/tcp;
    ufw allow 40000:50000/tcp; 
    if [[ "yes" == $INSTALL_SSL ]]; then 
        ufw allow 'Apache Secure';
    fi
    ufw_status=$(ufw status);

    if [[ $ufw_status != *"Status: active"* ]]; then
        good_print "To this question (Command may disrupt existing ssh connections. Proceed with operation (y|n)?) you can answer yes (y)";
        sleep 1;
        ufw enable;
    fi
    ufw status;
    good_print "Step 3 [Configuration UFW].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

apache_health_check(){
    good_print "***APACHE2 HEALTTH CHEACK***";
    sleep 1;
    good_print "At this stage you can check the Apache. Make a request from the browser or through curl http://ip_addr:port or http://$MAIN_DOMAIN:port You should see the start page and the Apache server.";
    get_approval;
    good_print "Step 4 [Apache health check].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_mysql(){
    good_print "***INSTALL MYSQL***";
    sleep 1;
    apt -y install mysql-server;
    if [[ 0 != $? ]]; then
        bad_print "install mysql failed";
        return 1;
    fi

    echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';" | mysql;

    good_print "We’re about to launch a security breach.";
    good_print "1. Enter the password you set for the root user in the previous step.";
    good_print "2. Plugin validation of your password is optional. That is the answer - N";
    good_print "3. If you are satisfied with the previously installed password for the root user, you do not need to change it. That is the answer - N":
    good_print "4. Anonymous user should be removed. That is the answer - Y";
    good_print "5. It is recommended to deny remote access. That is, the answer is - Y";
    good_print "6. The test database is better to delete. That is the answer - Y";
    good_print "7. It is recommended to reset all starting privileges. That is the answer - Y";

    get_approval;
    mysql_secure_installation;

    echo "CREATE USER '${MYSQL_ADMIN_USER}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ADMIN_PASSWORD}';" | mysql -u root -p${MYSQL_ROOT_PASSWORD};
    echo "GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_ADMIN_USER}'@'localhost' WITH GRANT OPTION;" | mysql -u root -p${MYSQL_ROOT_PASSWORD};
    
    good_print "Step 5 [install Mysql].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_php(){
    good_print "***INSTALL PHP***";
    sleep 1;
    add-apt-repository ppa:ondrej/php -y;
    apt update;
    apt-get -y install php-fpm php-mysql;
    if [[ 0 != $? ]]; then
        bad_print "install php libapache2-mod-php php-mysql failed";
        return 1;
    fi

    apt -y install php-curl php-json php-cgi php-gd php-zip php-mbstring php-xml php-xmlrpc;
    if [[ 0 != $? ]]; then
        bad_print "install php-curl php-json php-cgi php-gd php-zip php-mbstring php-xml php-xmlrpc failed";
        return 1;
    fi
    a2enmod proxy_fcgi setenvif;
    a2enconf php*.*-fpm;
    systemctl enable apache2;
    systemctl restart apache2;
   
    good_print "Step 6 [install PHP].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

create_main_domain(){
    good_print "***CREATE MAIN DOMAIN***";
    sleep 1;

    files=$(ls /var/run/php/);
    for file in $files; do
        type=$(file /var/run/php/$file);
        type=${type#*: };
        if [[ "socket" == $type ]]; then
            php_fpm_sock=$file;
        fi
    done

    mkdir "/var/www/$MAIN_DOMAIN";
    touch "/etc/apache2/sites-available/$MAIN_DOMAIN.conf";
    cat << EOF > "/etc/apache2/sites-available/$MAIN_DOMAIN.conf"
<VirtualHost *:80>
    ServerName $MAIN_DOMAIN
    ServerAlias www.$MAIN_DOMAIN
    ServerAdmin $ADMIN_EMAIL
    DocumentRoot /var/www/$MAIN_DOMAIN
    ErrorLog \${APACHE_LOG_DIR}/${MAIN_DOMAIN}_error.log
    CustomLog \${APACHE_LOG_DIR}/${MAIN_DOMAIN}_access.log combined

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/var/run/php/${php_fpm_sock}|fcgi://localhost/"

        # Else we can just use a tcp socket:
        #SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>

    <Directory /var/www/$MAIN_DOMAIN>
        Require all granted
        AllowOverride All
    </Directory>

</VirtualHost>
EOF
    a2ensite "$MAIN_DOMAIN.conf";
    systemctl reload apache2;
    apache2ctl configtest;
    sleep 1;

    sed -i 's/DirectoryIndex /DirectoryIndex index.php /' /etc/apache2/mods-enabled/dir.conf;
    systemctl reload apache2;
    good_print "Step 7 [Create main domain].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

create_sub_domain(){
    if [ -z ${SUBDOMAINS} ]; then
        return 1;
    else
        if [[ 0 < ${#SUBDOMAINS[@]} ]]; then 
            good_print "***CREATE SUB DOMAIN***";
            sleep 1;
        else
            return 1;    
        fi    
    fi
    
    files=$(ls /var/run/php/);
    for file in $files; do
        type=$(file /var/run/php/$file);
        type=${type#*: };
        if [[ "socket" == $type ]]; then
            php_fpm_sock=$file;
        fi
    done

    for subdomain in ${SUBDOMAINS[*]}; do 
        mkdir "/var/www/$subdomain";
        touch "/etc/apache2/sites-available/$subdomain.conf";
        cat << EOF > "/etc/apache2/sites-available/$subdomain.conf"
<VirtualHost *:80>
    ServerName $subdomain
    ServerAlias www.$subdomain
    ServerAdmin $ADMIN_EMAIL
    DocumentRoot /var/www/$subdomain
    ErrorLog \${APACHE_LOG_DIR}/${subdomain}_error.log
    CustomLog \${APACHE_LOG_DIR}/${subdomain}_access.log combined

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/var/run/php/${php_fpm_sock}|fcgi://localhost/"

        # Else we can just use a tcp socket:
        #SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>

    <Directory /var/www/$subdomain>
        Require all granted
        AllowOverride All
    </Directory>

</VirtualHost>
EOF

        a2ensite "$subdomain.conf";
        systemctl reload apache2;
    done

    apache2ctl configtest;
    good_print "Step 8 [Create sub domain].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

redirect_from_ip_to_main_domain(){
    good_print "***REDIRECT FROM IP TO MAIN DOMAIN***";
    sleep 1;
    mkdir "/var/www/default";
    cat << EOF > "/etc/apache2/sites-available/000-default.conf"
<VirtualHost *:80>
        ServerName $IP
        ServerAdmin $ADMIN_EMAIL
        DocumentRoot /var/www/default
        Redirect / http://$MAIN_DOMAIN$PORT
        ErrorLog \${APACHE_LOG_DIR}/error.log
        CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF
    systemctl restart apache2;
    apache2ctl configtest;
    good_print "Step 9 [Redirect from ip to main domain].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

test_php(){
    good_print "***TEST PHP***";
    sleep 1;
    touch "/var/www/$MAIN_DOMAIN/info.php";
    cat << EOF > "/var/www/$MAIN_DOMAIN/info.php"
<?php
phpinfo();
EOF
    good_print "Now you can check if php is working correctly. Query http://your_ip/info.php or http://$MAIN_DOMAIN/info.php";
    get_approval;
    rm "/var/www/$MAIN_DOMAIN/info.php";
    good_print "Step 10 [Test PHP].\nStatus: normal.\n";
    sleep 1;
    return 0;
}


test_php_and_mysql(){
    good_print "***TEST PHP AND MYSQL***";
    sleep 1;

    echo "CREATE DATABASE example_database;" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};
    echo "CREATE TABLE example_database.todo_list (item_id INT AUTO_INCREMENT,content VARCHAR(255),PRIMARY KEY(item_id));" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};
    echo "INSERT INTO example_database.todo_list (content) VALUES ( \"My first important item is\");" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};

    touch "/var/www/$MAIN_DOMAIN/todo_list.php";
    echo -e "<?php
    \$user = '${MYSQL_ADMIN_USER}';
    \$password = '${MYSQL_ADMIN_PASSWORD}';
    \$database = 'example_database';
    \$table = 'todo_list';" > "/var/www/$MAIN_DOMAIN/todo_list.php";

    echo -e 'try {
      $db = new PDO("mysql:host=localhost;dbname=$database", $user, $password);
      echo "<h2>TODO</h2><ol>";
      foreach($db->query("SELECT content FROM $table") as $row) {
        echo "<li>" . $row["content"] . "</li>";
      }
      echo "</ol>";
    } catch (PDOException $e) {
        print "Error!: " . $e->getMessage() . "<br/>";
        die();
    }' >> "/var/www/$MAIN_DOMAIN/todo_list.php";

    good_print "Now you can check if php and mysql are working correctly. Query http://your_ip/todo_list.php or http://$MAIN_DOMAIN/todo_list.php";
    get_approval;
    rm "/var/www/$MAIN_DOMAIN/todo_list.php";
    good_print "Step 11 [Test PHP and MySQL].\nStatus: normal.\n";
    sleep 1;
    return 0;

}

install_phpmyadmin(){
    good_print "***INSTALL PHPMYADMIN***";
    sleep 1;

    good_print "The installation of phpmyadmin will now be started";
    good_print "During the installation process, you will need to answer a few questions.";
    good_print "Here's a list of clues:";
    good_print "1. Use the Spacebar to select apache2, and then use Tab and Enter to press the OK button";
    good_print "2. Next, the installer will prompt to create a database for phpMyAdmin, which will contain the official information of the program and the necessary settings, you must agree to choose Yes:";
    good_print "Enter the password for the user phpmyadmin. You can use the same password as the adminer user.  Or any other password.";
    get_approval;
    apt-get -y install phpmyadmin;
    good_print "At this point, phpmyadmin is already available at http://your_ip/phpmyadmin or http://$MAIN_DOMAIN/phpmyadmin";
    get_approval;

    touch /usr/share/phpmyadmin/.htaccess;
    cat << EOF > "/usr/share/phpmyadmin/.htaccess"
AuthType Basic
AuthName "Restricted Files"
AuthUserFile /etc/phpmyadmin/.htpasswd
Require valid-user
EOF
    htpasswd -c /etc/phpmyadmin/.htpasswd adminer;
    cat << EOF >> "/etc/apache2/apache2.conf"
<Directory /usr/share>
    AllowOverride All
    Require all granted
</Directory>
EOF
    systemctl restart apache2;
    good_print "Step 12 [Install_phpmyqdmin].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_wordpress_cli(){
    good_print "***INSTALL WORDPRESS CLI***";
    sleep 1;
    curl -L https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /tmp/wp-cli.phar;
    chmod +x /tmp/wp-cli.phar;
    mv /tmp/wp-cli.phar /usr/bin/wp;
    good_print "Step 13 [Install wordpress cli].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_wordpress_for_main_domain(){
    good_print "***INSTALL WORDPRESS FOR MAIN DOMAIN***";
    sleep 1;
    
    cd /var/www/$MAIN_DOMAIN/;
    wp core download --force --allow-root;

    db_name=${MAIN_DOMAIN//./_};
    [ -f wp-config.php ] || wp config create --allow-root \
    --dbhost="localhost" \
    --dbname="${db_name}" \
    --dbuser="${MYSQL_ADMIN_USER}" \
    --dbpass="${MYSQL_ADMIN_PASSWORD}" \
    --dbprefix="${WP_DB_PREFIX}";
    
    echo "CREATE DATABASE ${db_name};" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};

    wp core install --allow-root\
    --url="http://${MAIN_DOMAIN}" \
    --title="${WP_SITE_TITLE}" \
    --admin_user="${WP_ADMIN_USER}" \
    --admin_password="${WP_ADMIN_PASSWORD}" \
    --admin_email="${WP_ADMIN_EMAIL}" \
    --skip-email

    echo "define('FS_METHOD', 'direct');" >> wp-config.php;
    wp plugin delete akismet hello --allow-root;
    wp option update blogdescription "${WP_SITE_DESCRIPTION}" --allow-root
    wp rewrite structure "${WP_PERMALINK_STRUCTURE}" --allow-root;
    wp theme activate "${WP_THEME_NAME}" --allow-root;
    wp theme delete twentytwenty twentytwentytwo twentytwentythree --allow-root;

    chown -R "${SYSTEM_USER_NAME}:www-data" "/var/www/";
    chmod -R "g+w" "/var/www/";
    good_print "Step 14 [Install wordpress for main domain].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

install_wordpress_for_sub_domain(){
    if [ -z ${SUBDOMAINS} ]; then
        return 1;
    else
        if [[ 0 < ${#SUBDOMAINS[@]} ]]; then 
            good_print "***INSTALL WORDPRESS FOR SUB DOMAIN***";
            sleep 1;
        else
            return 1;    
        fi    
    fi

    for subdomain in ${SUBDOMAINS[*]}; do

        cd /var/www/$subdomain/;
        wp core download --force --allow-root;

        db_name=${subdomain//./_};
        [ -f wp-config.php ] || wp config create --allow-root \
        --dbhost="localhost" \
        --dbname="${db_name}" \
        --dbuser="${MYSQL_ADMIN_USER}" \
        --dbpass="${MYSQL_ADMIN_PASSWORD}" \
        --dbprefix="${WP_DB_PREFIX}";
    
        echo "CREATE DATABASE ${db_name};" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};

        wp core install --allow-root \
        --url="http://${subdomain}" \
        --title="${WP_SITE_TITLE}" \
        --admin_user="${WP_ADMIN_USER}" \
        --admin_password="${WP_ADMIN_PASSWORD}" \
        --admin_email="${WP_ADMIN_EMAIL}" \
        --skip-email

        echo "define('FS_METHOD', 'direct');" >> wp-config.php;
        wp plugin delete akismet hello --allow-root;
        wp option update blogdescription "${WP_SITE_DESCRIPTION}" --allow-root
        wp rewrite structure "${WP_PERMALINK_STRUCTURE}" --allow-root;
        wp theme activate "${WP_THEME_NAME}" --allow-root;
        wp theme delete twentytwenty twentytwentytwo twentytwentythree --allow-root;

        chown -R "${SYSTEM_USER_NAME}:www-data" "/var/www/";
        chmod -R "g+w" "/var/www/";
    done
    good_print "Step 15 [Install wordpress for sub domain].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

delete_unnecessary(){
    good_print "***DELETE UNNECESSARY***";
    sleep 1;
    rm -rf "/var/www/html";
    echo "DROP DATABASE IF EXISTS example_database;" | mysql -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD};
    good_print "Step 16 [Delete unnecessary].\nStatus: normal.\n";
    sleep 1;
    return 0;
}

#basic_protection?
#install_vsftpd?
#add_user_in_additional_group?
#install_zabbix?
#install_ssl?
#create_backup_script?

#**
#*RUN
#**
preparatory_step;
create_user;
install_apache;
configuration_ufw;
apache_health_check;
install_mysql;
install_php;
create_main_domain;
create_sub_domain;
redirect_from_ip_to_main_domain;
test_php;
test_php_and_mysql;
install_phpmyadmin;
install_wordpress_cli;
install_wordpress_for_main_domain;
install_wordpress_for_sub_domain;
delete_unnecessary;

cat << EOF
************
****DONE****
************
EOF
echo "
           ▄▄▄▄
           █░░█
           █░░█
           █░░░█
         █░░░░░█
███████▄▄█░░░░░██████▄
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░░█
▓▓scriptcraft.site ░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█████░░░░░░░░░█
██████▀░░░░▀▀█████▀ ";