#!/bin/bash

#**
#*Signature
#*https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-18-04-server-ru
#*https://alto.codes/blog/dev/nastraivaem-web-server-nginx-and-apache.html
#*https://www.8host.com/blog/nginx-kak-veb-server-i-proksi-server-dlya-apache-v-ubuntu-20-04/
#**